name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Scarica il codice
      uses: actions/checkout@v4

    - name: Installa Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installa Flet
      run: |
        python -m pip install --upgrade pip
        pip install flet

    - name: Compila l'APK per Android (Verbose)
      run: |
        flet build apk -v

    - name: Salva l'APK come file scaricabile
      uses: actions/upload-artifact@v4
      with:
        name: app-android
        path: build/apk/*.apk
